### ISSUE TITLE
Update HTTP.jl to v1.0.x

### ISSUE THREAD

**Issue by PhyX-Meow** [Arkoniak/Telegram.jl#16]
HTTP.jl recently have a major verion update to v1.0,  which breaks some old functionality and add many new ones, my project need to depend on new HTTP.jl and your project.
So is there any chance to update dependence of Telegram.jl?I may open a pull request later after I test new version locally.
Btw, does this project still maintained? Seems it does not get updated for quite a while.

**Comment by PhyX-Meow** [comment]
Closed by https://github.com/Arkoniak/Telegram.jl/pull/17

**Comment by Arkoniak** [comment]
Thank you for your commit, package has been updated with new HTTP.jl version.

Project is maintained, it's just that there is not much to do here other then occasional updates.
