### ISSUE TITLE
Add an easier way to handle messages?

### ISSUE THREAD

**Issue by nm17** [Arkoniak/Telegram.jl#6]
For reference: aiogram library

**Comment by Arkoniak** [comment]
Can you elaborate, what exactly is proposed? What are the current issues with message handling and how it can be improved?

Just as a note: Telegram.jl was built as a thin wrapper over Telegram Bot api with minimal restrictions and additions, so one can use it later to implement more sophisticated libraries.

**Comment by nm17** [comment]
@Arkoniak I was thinking of something like this: 
```python
@dp.message_handler(commands=['start', 'help'])
async def send_welcome(message: types.Message):
    """
    This handler will be called when user sends `/start` or `/help` command
    """
    await message.reply("Hi!\nI'm EchoBot!\nPowered by aiogram.")
```
Can we have something similiar to `dp.message_handler` context manager in Telegram.jl?

**Comment by Arkoniak** [comment]
Ok, I can think of the following design.

1. User can generate dictionary which maps commands to functions.
2. User pass this dictionary to `run_bot` function.

It looks like this

```julia
function send_welcome(client, msg)
    sendMessage(client, text = "Hi!\nI'm EchoBot!")
end

commands = Dict(r"start|help" => send_welcome)

run_bot(commands)
```

Here `msg` contains original message in case you need to parse it additionally. 

As a second thought, we can add commands as an optional keyword, which will catch commands. If there is no command found for this particular message it uses default function

```julia
run_bot(commands = commands) do msg
   sendMessage(text = msg.message.text)
end
```

So it will return "Hi! I'm EchoBot" for "/help" or "/start", and copy of original message in all other cases.

**Comment by Arkoniak** [comment]
No resolution was found, so I am close this issue. Feel free to reopen it if any viable approach is found.
